<?php

namespace AppBundle\Repository;

/**
 * DressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DressRepository extends \Doctrine\ORM\EntityRepository
{
}
